### PR TITLE
Allow changing AirWindow by MIDI program change messages. 

### PR DESCRIPTION
**Pull request by Xenakios**
Not sure if this is too esoteric to be merged? Anyway, presenting this for consideration. 

I realize there's the problem with this is that when new AirWindows are added, existing program change messages in DAW sequences etc will no longer select the same AirWindow, but that is a problem I would personally be willing to live with.

### CODE REVIEW

**Comment by baconpaul** [comment]
So the lack of stability is exactly why I was worried about this class of thing. Any ideas to solve that?

**Comment by baconpaul** [comment]
One idea would be to put this behind an off by default user option and add to the manual for instance. Another would be to program change by commit date order which is now a field in the registry.

**Comment by Xenakios** [comment]
> One idea would be to put this behind an off by default user option and add to the manual for instance. Another would be to program change by commit date order which is now a field in the registry.

Ok, I am working on a different approach to this. (An optional JSON config file.) Having an enable toggle for this in the GUI is not great for me because the whole purpose of attempting this is to avoid having to use the GUI.

**Comment by baconpaul** [comment]
Right so the reason I didn’t make effect a param or a midi change is because the list changes weekly and there’s no good migration strategy 

Now we have commit date we could do program changes based on those as a preference. Preferences are stored in a file already so you can just edit that file if you plan to never ever use the fui, or just toggle it once 

so a midi program change behind a preference with a menu stored like the other preferences which indexed in commit date order is something I’d merge - otherwise I’m reticent because the non reproducible behavior over versions would be a rather high support burden 

also need to test if the au still loads properly in logic and live with midi input activated - that can be tricky

**Comment by Xenakios** [comment]
OK, I am going to rethink this and close this pull request now

**Comment by baconpaul** [comment]
Yeah 

another approach is write a separate plugin using the static library here - the rack and juce plugins are just “thin” wrappers on the registry - and then allow users to configure effects and settings in a bank as a prefrrrnce

**Pull request closed without merging**
